const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  BRAND_OWNER: 'BRAND_OWNER',
  OUTLET_MANAGER: 'OUTLET_MANAGER',
  ARM: 'ARM',
  GSA: 'GSA',
  CASHIER: 'CASHIER',
  CAPTAIN: 'CAPTAIN',
  KITCHEN: 'KITCHEN',
  VENDOR: 'VENDOR'
};

module.exports = { ROLES };